create extension if not exists pgcrypto;
create sequence if not exists public.punch_id_seq start 1 increment 1;

do $$ begin create type public.user_role as enum ('employee','admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.account_status as enum ('pending','approved','rejected','inactive'); exception when duplicate_object then null; end $$;
do $$ begin create type public.attendance_status as enum ('Present','Absent','Leave','Holiday'); exception when duplicate_object then null; end $$;
do $$ begin create type public.leave_status as enum ('pending','approved','rejected'); exception when duplicate_object then null; end $$;

create table if not exists public.shifts(id uuid primary key default gen_random_uuid(),name text not null,start_time time not null,end_time time not null,grace_minutes integer not null default 0 check(grace_minutes>=0),created_at timestamptz not null default now());
create table if not exists public.locations(id uuid primary key default gen_random_uuid(),name text not null,lat double precision not null check(lat between -90 and 90),lng double precision not null check(lng between -180 and 180),radius_m integer not null default 20 check(radius_m>0 and radius_m<=5000),is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,punch_id bigint unique not null default nextval('public.punch_id_seq'),name text not null,email text not null unique,phone text,role public.user_role not null default 'employee',status public.account_status not null default 'pending',photo_url text,shift_id uuid references public.shifts(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.employee_locations(user_id uuid references public.profiles(id) on delete cascade,location_id uuid references public.locations(id) on delete cascade,assigned_at timestamptz not null default now(),primary key(user_id,location_id));
create table if not exists public.attendance(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,date date not null,punch_in timestamptz,punch_out timestamptz,in_lat double precision,in_lng double precision,in_accuracy double precision,in_distance_m double precision,in_selfie_url text,in_location_id uuid references public.locations(id) on delete set null,out_lat double precision,out_lng double precision,out_accuracy double precision,out_distance_m double precision,out_selfie_url text,out_location_id uuid references public.locations(id) on delete set null,status public.attendance_status not null default 'Present',flagged boolean not null default false,flag_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,date));
create table if not exists public.leaves(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,start_date date not null,end_date date not null,reason text not null,status public.leave_status not null default 'pending',reviewed_by uuid references public.profiles(id) on delete set null,reviewed_at timestamptz,created_at timestamptz not null default now(),check(end_date>=start_date));
create table if not exists public.daily_welcome(date date primary key,image_url text,message text,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),admin_id uuid references public.profiles(id) on delete set null,action text not null,target_type text,target_id text,details jsonb,created_at timestamptz not null default now());
create table if not exists public.holidays(date date primary key,name text not null,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.rate_limit_events(id bigserial primary key,key text not null,created_at timestamptz not null default now());
create index if not exists idx_attendance_user_date on public.attendance(user_id,date desc);create index if not exists idx_attendance_date on public.attendance(date desc);create index if not exists idx_leaves_user on public.leaves(user_id,start_date desc);create index if not exists idx_profiles_status on public.profiles(status);create index if not exists idx_audit_created on public.audit_logs(created_at desc);create index if not exists idx_rate_limit_key_time on public.rate_limit_events(key,created_at desc);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,name,email,phone) values(new.id,coalesce(new.raw_user_meta_data->>'name','Employee'),new.email,new.raw_user_meta_data->>'phone');return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='admin' and status='approved');$$;

alter table public.profiles enable row level security;alter table public.locations enable row level security;alter table public.employee_locations enable row level security;alter table public.attendance enable row level security;alter table public.leaves enable row level security;alter table public.daily_welcome enable row level security;alter table public.audit_logs enable row level security;alter table public.shifts enable row level security;alter table public.rate_limit_events enable row level security;alter table public.holidays enable row level security;

drop policy if exists profiles_self on public.profiles;drop policy if exists profiles_update_self on public.profiles;drop policy if exists admin_profiles_all on public.profiles;
create policy profiles_self on public.profiles for select using(id=auth.uid() or public.is_admin());create policy admin_profiles_all on public.profiles for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists locations_employee_read on public.locations;drop policy if exists locations_admin_all on public.locations;create policy locations_employee_read on public.locations for select using(public.is_admin() or (is_active and exists(select 1 from employee_locations el where el.location_id=id and el.user_id=auth.uid())));create policy locations_admin_all on public.locations for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists emp_loc_self_read on public.employee_locations;drop policy if exists emp_loc_admin_all on public.employee_locations;create policy emp_loc_self_read on public.employee_locations for select using(user_id=auth.uid() or public.is_admin());create policy emp_loc_admin_all on public.employee_locations for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists attendance_self on public.attendance;drop policy if exists attendance_admin_all on public.attendance;create policy attendance_self on public.attendance for select using(user_id=auth.uid() or public.is_admin());create policy attendance_admin_all on public.attendance for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists leaves_self on public.leaves;drop policy if exists leaves_insert_self on public.leaves;drop policy if exists leaves_admin_all on public.leaves;create policy leaves_self on public.leaves for select using(user_id=auth.uid() or public.is_admin());create policy leaves_insert_self on public.leaves for insert with check(user_id=auth.uid() and status='pending' and reviewed_by is null and reviewed_at is null);create policy leaves_admin_all on public.leaves for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists welcome_read on public.daily_welcome;drop policy if exists welcome_admin on public.daily_welcome;create policy welcome_read on public.daily_welcome for select using(auth.uid() is not null);create policy welcome_admin on public.daily_welcome for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists audit_admin on public.audit_logs;create policy audit_admin on public.audit_logs for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists shifts_read on public.shifts;drop policy if exists shifts_admin on public.shifts;create policy shifts_read on public.shifts for select using(auth.uid() is not null);create policy shifts_admin on public.shifts for all using(public.is_admin()) with check(public.is_admin());

insert into storage.buckets(id,name,public) values('profile-photos','profile-photos',false) on conflict(id) do nothing;insert into storage.buckets(id,name,public) values('punch-selfies','punch-selfies',false) on conflict(id) do nothing;insert into storage.buckets(id,name,public) values('welcome-posters','welcome-posters',false) on conflict(id) do nothing;
drop policy if exists storage_profile_read on storage.objects;drop policy if exists storage_profile_insert on storage.objects;drop policy if exists storage_profile_update on storage.objects;drop policy if exists storage_selfie_admin on storage.objects;drop policy if exists storage_selfie_self on storage.objects;drop policy if exists storage_welcome_admin on storage.objects;
create policy storage_profile_read on storage.objects for select to authenticated using(bucket_id='profile-photos' and (owner_id=auth.uid()::text or public.is_admin()));create policy storage_profile_insert on storage.objects for insert to authenticated with check(bucket_id='profile-photos' and owner_id=auth.uid()::text);create policy storage_profile_update on storage.objects for update to authenticated using(bucket_id='profile-photos' and (owner_id=auth.uid()::text or public.is_admin()));
create policy storage_selfie_admin on storage.objects for select to authenticated using(bucket_id='punch-selfies' and public.is_admin());create policy storage_selfie_self on storage.objects for select to authenticated using(bucket_id='punch-selfies' and name like auth.uid()::text || '/%');create policy storage_welcome_admin on storage.objects for all to authenticated using(bucket_id='welcome-posters' and public.is_admin()) with check(bucket_id='welcome-posters' and public.is_admin());

create or replace function public.consume_rate_limit(p_key text,p_max integer,p_window_seconds integer) returns boolean language plpgsql security definer set search_path=public as $$declare n integer;begin delete from rate_limit_events where created_at < now() - make_interval(secs=>p_window_seconds);select count(*) into n from rate_limit_events where key=p_key and created_at >= now() - make_interval(secs=>p_window_seconds);if n >= p_max then return false;end if;insert into rate_limit_events(key) values(p_key);return true;end;$$;
revoke all on function public.consume_rate_limit(text,integer,integer) from public,anon,authenticated;
grant execute on function public.consume_rate_limit(text,integer,integer) to service_role;

create or replace function public.dashboard_counts(p_date date) returns table(present bigint,absent bigint,late bigint,pending bigint) language sql security definer set search_path=public as $$select (select count(*) from attendance where date=p_date and punch_in is not null),(select count(*) from profiles p where p.role='employee' and p.status='approved' and not exists(select 1 from attendance a where a.user_id=p.id and a.date=p_date and a.punch_in is not null)),(select count(*) from attendance a join profiles p on p.id=a.user_id join shifts s on s.id=p.shift_id where a.date=p_date and a.punch_in is not null and (a.punch_in at time zone 'Asia/Kolkata')::time > (s.start_time + make_interval(mins=>s.grace_minutes))),(select count(*) from profiles where status='pending');$$;
revoke all on function public.dashboard_counts(date) from public,anon,authenticated;grant execute on function public.dashboard_counts(date) to service_role;

create or replace function public.promote_first_user_to_admin() returns public.profiles language plpgsql security definer set search_path=public as $$declare r public.profiles;begin if exists(select 1 from profiles where role='admin') then raise exception 'An admin already exists'; end if; select * into r from profiles order by created_at asc limit 1; if r.id is null then raise exception 'Create the first Auth user before running this function'; end if; update profiles set role='admin',status='approved',updated_at=now() where id=r.id returning * into r; return r; end;$$;
revoke all on function public.promote_first_user_to_admin() from public,anon,authenticated;grant execute on function public.promote_first_user_to_admin() to service_role;

drop policy if exists holidays_read on public.holidays;drop policy if exists holidays_admin on public.holidays;
create policy holidays_read on public.holidays for select using(auth.uid() is not null);
create policy holidays_admin on public.holidays for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists storage_welcome_read on storage.objects;
create policy storage_welcome_read on storage.objects for select to authenticated using(bucket_id='welcome-posters');
